# Generated by Django 5.1.7 on 2025-03-19 06:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('preferred_job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance')], max_length=20)),
                ('skills', models.TextField()),
                ('experience', models.TextField()),
                ('cv', models.FileField(help_text='Upload your CV in PDF or Word format', upload_to='candidates/cv/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('profile_picture', models.ImageField(help_text='Upload your professional profile picture', upload_to='candidates/profile_pictures/')),
                ('additional_pictures', models.ImageField(blank=True, help_text='Upload additional professional pictures', upload_to='candidates/additional_pictures/')),
                ('photo_id', models.FileField(help_text='Upload your photo ID for verification', upload_to='candidates/photo_ids/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('industry', models.CharField(choices=[('TECH', 'Technology'), ('HEALTHCARE', 'Healthcare'), ('RETAIL', 'Retail'), ('HOSPITALITY', 'Hospitality'), ('EVENTS', 'Events'), ('OTHER', 'Other')], max_length=20)),
                ('gst_number', models.CharField(max_length=15, unique=True)),
                ('company_address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('company_website', models.URLField(blank=True)),
                ('company_logo', models.ImageField(blank=True, help_text='Upload your company logo', upload_to='clients/logos/')),
                ('preferred_candidate_requirements', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('GST', 'GST Certificate'), ('PAN', 'PAN Card'), ('INCORP', 'Incorporation Certificate'), ('OTHER', 'Other')], max_length=10)),
                ('document', models.FileField(help_text='Upload verification document', upload_to='clients/verification_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='profiles.clientprofile')),
            ],
        ),
    ]
