# Generated by Django 5.1.7 on 2025-03-21 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='additional_pictures',
            field=models.ImageField(blank=True, help_text='Optional: Upload additional professional pictures', null=True, upload_to='candidates/additional_pictures/'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='cv',
            field=models.FileField(help_text='Upload your CV in PDF or Word format', upload_to='candidates/cv/'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='experience',
            field=models.TextField(help_text='Describe your work experience and achievements'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(help_text='Enter your primary contact number', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='photo_id',
            field=models.ImageField(help_text='Upload your photo ID for verification', upload_to='candidates/photo_id/'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.ImageField(help_text='Upload a professional headshot', upload_to='candidates/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(help_text='List your key skills, separated by commas'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Optional: For faster communication with employers', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
    ]
