# Generated by Django 5.1.7 on 2025-05-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobapplication_cover_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_range',
            field=models.CharField(choices=[('0-20000', '₹0 - ₹20,000'), ('20000-50000', '₹20,000 - ₹50,000'), ('50000-100000', '₹50,000 - ₹1,00,000'), ('100000+', '₹1,00,000+')], max_length=20),
        ),
    ]
