databases:
  - name: paydayzz-db
    databaseName: paydayzz
    user: paydayzz_user
    plan: free

services:
  - type: web
    name: paydayzz-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn paydayzz.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: paydayzz-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: CORS_ALLOW_ALL_ORIGINS
        value: True 