# Generated by Django 5.1.7 on 2025-03-28 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('job_alert', 'Job Alert to Candidate'), ('application', 'Application Alert to Client')], max_length=20)),
                ('recipient_phone', models.CharField(max_length=15)),
                ('recipient_name', models.CharField(max_length=100)),
                ('content', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification_type'], name='notificatio_notific_5cd8cf_idx'), models.Index(fields=['status'], name='notificatio_status_60f761_idx'), models.Index(fields=['recipient_phone'], name='notificatio_recipie_d47cd6_idx')],
            },
        ),
    ]
